# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dispen_map <- function(x, ma, nc, mu, sigma) {
    .Call(`_MSEntropy_dispen_map`, x, ma, nc, mu, sigma)
}

dispen_npdf <- function(z, nc, m, tau) {
    .Call(`_MSEntropy_dispen_npdf`, z, nc, m, tau)
}

fdispen_npdf <- function(z, nc, m, tau) {
    .Call(`_MSEntropy_fdispen_npdf`, z, nc, m, tau)
}

sampen <- function(data, m, r, N, sd) {
    .Call(`_MSEntropy_sampen`, data, m, r, N, sd)
}

#' Signal Scaling (coarse-grained by average)
#'
#' @param x the signal as a numeric vector
#' @param scale the scaling factor
#'
#' @export
CoarseGraining <- function(x, scale) {
    .Call(`_MSEntropy_CoarseGraining`, x, scale)
}

