# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

disen_map <- function(x, ma, nc, mu, sigma) {
    .Call(`_MSEntropy_disen_map`, x, ma, nc, mu, sigma)
}

disen_npdf <- function(z, nc, m, tau) {
    .Call(`_MSEntropy_disen_npdf`, z, nc, m, tau)
}

fdisen_npdf <- function(z, nc, m, tau) {
    .Call(`_MSEntropy_fdisen_npdf`, z, nc, m, tau)
}

#' Signal Scaling (coarse-grained by average)
#'
#' @param x the signal as a numeric vector
#' @param scale the scaling factor
#'
#' @export
CoarseGraining <- function(x, scale) {
    .Call(`_MSEntropy_CoarseGraining`, x, scale)
}

